version: '3'

services:
  reverse-proxy:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/home/marina/gitea_docker/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gitea

  gitea:
    image: gitea/gitea:1.21.0
    volumes:
      - ./gitea:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=https://localhost:3000/
      - DISABLE_SSH=true
      - DB_TYPE=sqlite3
      - DB_PATH=/data/gitea.db
      - APP_NAME=Gitea  
    ports:
      - "3000:3000"  
    depends_on:
      - db

  db:
   image: postgres
   environment:
     POSTGRES_USER: gitea
     POSTGRES_PASSWORD: gitea
     POSTGRES_DB: gitea
   volumes:
     - ./postgres-data:/var/lib/postgresql/data
