version: '3'

services:
  reverse-proxy:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/home/marina/gitea_docker/nginx.conf
    ports:
      - "80:80"
      - "443:443"

  gitea:
    image: gitea/gitea:1.21.0
    volumes:
      - /var/lib/gitea:/data
      - /home/marina/gitea_docker/gitea:/repositories
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=https://localhost
      - DOMAIN=localhost
      - SSH_DOMAIN=localhost
      - DISABLE_SSH=true
      - DB_TYPE=sqlite3
      - DB_PATH=/data/gitea.db
      - LOG_MODE=console
      - INSTALL_LOCK=true
    ports:
      - "3000:3000"  
    depends_on:
      - reverse-proxy

volumes:
  gitea_data:
